#!/usr/bin/env python3
"""Prepare Uni-Dock box manifest from audited Q10 HEM/Fe receptors.

Formal Q10 docking uses receptors generated by
q10_build_heme_fe_receptors_20260528.py. Box centers are Fe coordinates from
the receptor manifest. Protein-only ColabFold structures are deliberately not
used as formal Uni-Dock receptors here.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List


BOX_SIZE = 22.5


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: List[Dict[str, object]], fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def truthy_number(value: str) -> bool:
    try:
        return float(value) > 0
    except Exception:
        return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--q10-dir", required=True)
    parser.add_argument("--structure-manifest", default="")
    parser.add_argument("--receptor-manifest", default="")
    parser.add_argument("--box-size", type=float, default=BOX_SIZE)
    parser.add_argument("--allow-non-good-fe-cys", action="store_true")
    args = parser.parse_args()

    q10_dir = Path(args.q10_dir).resolve()
    structure_manifest = Path(args.structure_manifest) if args.structure_manifest else (
        q10_dir / "structures" / "manifests" / "q10_colabfold_structure_manifest_msa_m1r1_v1.csv"
    )
    receptor_manifest = Path(args.receptor_manifest) if args.receptor_manifest else (
        q10_dir / "structures" / "manifests" / "q10_heme_fe_receptor_manifest_template_v1.csv"
    )
    out_manifest = q10_dir / "docking" / "manifests" / "q10_unidock_box_manifest_msa_m1r1_v1.csv"
    out_summary = q10_dir / "docking" / "manifests" / "q10_unidock_box_summary_msa_m1r1_v1.json"

    structure_by_candidate = {row["candidate_id"]: row for row in read_csv(structure_manifest)}
    receptor_rows = read_csv(receptor_manifest)
    out_rows: List[Dict[str, object]] = []
    skipped: Dict[str, int] = {}

    for row in receptor_rows:
        candidate_id = row.get("candidate_id", "")
        if row.get("status") != "ok":
            skipped["receptor_not_ok"] = skipped.get("receptor_not_ok", 0) + 1
            continue
        if not truthy_number(row.get("n_fe_atoms", "")):
            skipped["missing_fe"] = skipped.get("missing_fe", 0) + 1
            continue
        if row.get("heme_fe_quality") != "good_fe_cys" and not args.allow_non_good_fe_cys:
            skipped["non_good_fe_cys"] = skipped.get("non_good_fe_cys", 0) + 1
            continue
        receptor_pdb = Path(row["receptor_pdb"])
        if not receptor_pdb.exists():
            skipped["missing_receptor_pdb"] = skipped.get("missing_receptor_pdb", 0) + 1
            continue
        if not row.get("fe_x") or not row.get("fe_y") or not row.get("fe_z"):
            skipped["missing_fe_coordinates"] = skipped.get("missing_fe_coordinates", 0) + 1
            continue

        struct = structure_by_candidate.get(candidate_id, {})
        receptor_pdbqt = q10_dir / "docking" / "receptors_pdbqt" / f"{candidate_id}.pdbqt"
        workdir = q10_dir / "docking" / "proteinprep_work" / candidate_id
        out_rows.append(
            {
                "candidate_id": candidate_id,
                "input_list": row["input_list"],
                "fasta_header": struct.get("fasta_header", candidate_id),
                "sequence_length": struct.get("sequence_length", ""),
                "mean_plddt": row.get("mean_plddt") or struct.get("mean_plddt", ""),
                "ptm": row.get("ptm") or struct.get("ptm", ""),
                "receptor_pdb_path": str(receptor_pdb),
                "receptor_pdbqt_path": str(receptor_pdbqt),
                "proteinprep_workdir": str(workdir),
                "heme_present_in_predicted_pdb": True,
                "fe_present_in_predicted_pdb": True,
                "box_source": "template_overlay_fe_center",
                "motif_pattern": "",
                "motif_text": "",
                "motif_cys_index_1based": row.get("nearest_cys_resseq", ""),
                "center_atom_note": "Fe from HEM/Fe receptor overlay",
                "center_x": row["fe_x"],
                "center_y": row["fe_y"],
                "center_z": row["fe_z"],
                "size_x": args.box_size,
                "size_y": args.box_size,
                "size_z": args.box_size,
                "proteinprep_status": "pending",
                "proteinprep_error": "",
                "heme_fe_quality": row.get("heme_fe_quality", ""),
                "nearest_cys_sg_fe_distance": row.get("nearest_cys_sg_fe_distance", ""),
                "template_pdb_id": row.get("template_pdb_id", ""),
                "template_uniprot": row.get("template_uniprot", ""),
                "fit_rmsd": row.get("fit_rmsd", ""),
            }
        )

    fieldnames = [
        "candidate_id",
        "input_list",
        "fasta_header",
        "sequence_length",
        "mean_plddt",
        "ptm",
        "receptor_pdb_path",
        "receptor_pdbqt_path",
        "proteinprep_workdir",
        "heme_present_in_predicted_pdb",
        "fe_present_in_predicted_pdb",
        "box_source",
        "motif_pattern",
        "motif_text",
        "motif_cys_index_1based",
        "center_atom_note",
        "center_x",
        "center_y",
        "center_z",
        "size_x",
        "size_y",
        "size_z",
        "proteinprep_status",
        "proteinprep_error",
        "heme_fe_quality",
        "nearest_cys_sg_fe_distance",
        "template_pdb_id",
        "template_uniprot",
        "fit_rmsd",
    ]
    write_csv(out_manifest, out_rows, fieldnames)

    by_list: Dict[str, int] = {}
    by_quality: Dict[str, int] = {}
    for out in out_rows:
        by_list[str(out["input_list"])] = by_list.get(str(out["input_list"]), 0) + 1
        by_quality[str(out["heme_fe_quality"])] = by_quality.get(str(out["heme_fe_quality"]), 0) + 1
    summary = {
        "structure_manifest": str(structure_manifest),
        "receptor_manifest": str(receptor_manifest),
        "box_manifest": str(out_manifest),
        "complete_receptors": len(out_rows),
        "by_input_list": by_list,
        "by_heme_fe_quality": by_quality,
        "skipped": skipped,
        "box_size": args.box_size,
        "note": "Formal Q10 Uni-Dock boxes use Fe coordinates from HEM/Fe receptor overlay.",
    }
    out_summary.parent.mkdir(parents=True, exist_ok=True)
    out_summary.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
